import { Movie } from ".";

export const FILMS: Movie[] = [
    {
        id: '1',
        title: 'Pulp Fiction',
        genres: [5],
        year: 2004,
        coverUrl: '/assets/covers/pulp_fiction.jpg',
        rating: 8.9,
        duration: 154,
    },
    {
        id: '2',
        title: 'Bohemian Rhapsody',
        genres: [6, 7, 8],
        year: 2003,
        coverUrl: '/assets/covers/bohemian_rhapsodia.jpg',
        rating: 8.9,
        duration: 154,
    },
    {
        id: '3',
        title: 'Kill Bill: Vol 2',
        genres: [9],
        year: 1994,
        coverUrl: '/assets/covers/kill_bill.jpg',
        rating: 8.9,
        duration: 154,
    },
    {
        id: '4',
        title: 'Avengers: War of Infinity',
        genres: [5],
        year: 2004,
        coverUrl: '/assets/covers/avengers.jpg',
        rating: 8.9,
        duration: 154,
    },
    {
        id: '5',
        title: 'Inception',
        genres: [5],
        year: 2003,
        coverUrl: '/assets/covers/inception.jpg',
        rating: 8.9,
        duration: 154,
    },
    {
        id: '6',
        title: 'Reservoir dogs',
        genres: [9],
        year: 1994,
        coverUrl: '/assets/covers/reservoir_dogs.jpg',
        rating: 8.9,
        duration: 154,
    },
]
